title: Project

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: text

pages: false

fields:
  title:
    label: Title
    type:  text
	
  subtitle:
	  label: Subtitle
	  type: text
	  
  line:
      type: line
	
  cover_image:
      label: Cover
      type: image
  
  line_2:
      type: line

  featured_video:
      label: Video Embed
      type: oembed
	  preview:    true
      info:       false
      cheatsheet: false
      height:     250px
      
	 
